export const AuditEventType = {
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_CLAIMED: 'TICKET_CLAIMED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  MESSAGE_ADDED: 'MESSAGE_ADDED',
  INTERNAL_NOTE_ADDED: 'INTERNAL_NOTE_ADDED',
  TICKET_RESOLVED: 'TICKET_RESOLVED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_REOPENED: 'TICKET_REOPENED',
  AI_ANALYSIS_CREATED: 'AI_ANALYSIS_CREATED',
  AI_SUMMARY_CREATED: 'AI_SUMMARY_CREATED',
  AI_REPLY_GENERATED: 'AI_REPLY_GENERATED',
  AI_REPLY_SENT: 'AI_REPLY_SENT',
  TICKET_UPDATED: 'TICKET_UPDATED',
  TICKET_DELETED: 'TICKET_DELETED',
} as const;

export type AuditEventTypeType = (typeof AuditEventType)[keyof typeof AuditEventType];

export const NotificationType = {
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  AGENT_REPLIED: 'AGENT_REPLIED',
  CUSTOMER_REPLIED: 'CUSTOMER_REPLIED',
  TICKET_UPDATED: 'TICKET_UPDATED',
  TICKET_RESOLVED: 'TICKET_RESOLVED',
  TICKET_REOPENED: 'TICKET_REOPENED',
} as const;

export type NotificationTypeType = (typeof NotificationType)[keyof typeof NotificationType];
